name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        type: boolean
        required: false
      custom_message:
        type: string
        description: 'Enter a custom message'  
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "Custom message is  ${{inputs.custom_message}}"