name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        type: boolean
        required: false
        description: 'Run Specific Job'
      custom_message:
        type: string
        description: 'Enter a custom message'  
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "Custom message is  ${{inputs.custom_message}}"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Printing run-job boolean value
        if: inputs.run-job == 'true'
        run: echo "boolean value is ${{inputs.run-job}}"